"""Seed migration

Revision ID: a8767b429b02
Revises:
Create Date: 2022-04-08 17:19:34.432371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8767b429b02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token')
    )
    op.create_table('tradables',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('enabled', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('account_balances',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('time', sa.DateTime(), nullable=True),
        sa.Column('cash', sa.Numeric(), nullable=False),
        sa.Column('value', sa.Numeric(), nullable=False),
        sa.Column('initial', sa.Numeric(), nullable=False),
        sa.Column('account_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('symbol', sa.String(), nullable=True),
        sa.Column('exchange', sa.String(), nullable=True),
        sa.Column('expirationtype', sa.String(), nullable=True),
        sa.Column('strike', sa.Numeric(), nullable=True),
        sa.Column('expiration', sa.Date(), nullable=True),
        sa.Column('tradable_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['tradable_id'], ['tradables.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options_fetch',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tradable_id', sa.Integer(), nullable=True),
        sa.Column('time', sa.DateTime(), nullable=True),
        sa.Column('volatility', sa.Numeric(), nullable=True),
        sa.Column('oi', sa.Integer(), nullable=True),
        sa.Column('volume', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['tradable_id'], ['tradables.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options_data',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ask', sa.Numeric(), nullable=True),
        sa.Column('asksize', sa.Numeric(), nullable=True),
        sa.Column('bid', sa.Numeric(), nullable=True),
        sa.Column('bidsize', sa.Numeric(), nullable=True),
        sa.Column('close', sa.Numeric(), nullable=True),
        sa.Column('dte', sa.Integer(), nullable=True),
        sa.Column('delta', sa.Numeric(), nullable=True),
        sa.Column('gamma', sa.Numeric(), nullable=True),
        sa.Column('low', sa.Numeric(), nullable=True),
        sa.Column('high', sa.Numeric(), nullable=True),
        sa.Column('itm', sa.Boolean(), nullable=True),
        sa.Column('last', sa.Numeric(), nullable=True),
        sa.Column('lastsize', sa.Numeric(), nullable=True),
        sa.Column('mark', sa.Numeric(), nullable=True),
        sa.Column('markchange', sa.Numeric(), nullable=True),
        sa.Column('rho', sa.Numeric(), nullable=True),
        sa.Column('theovalue', sa.Numeric(), nullable=True),
        sa.Column('theovol', sa.Numeric(), nullable=True),
        sa.Column('theta', sa.Numeric(), nullable=True),
        sa.Column('timevalue', sa.Numeric(), nullable=True),
        sa.Column('volume', sa.Numeric(), nullable=True),
        sa.Column('vega', sa.Numeric(), nullable=True),
        sa.Column('volatility', sa.Numeric(), nullable=True),
        sa.Column('time', sa.DateTime(), nullable=True),
        sa.Column('underlying', sa.Numeric(), nullable=True),
        sa.Column('riskfree', sa.Numeric(), nullable=True),
        sa.Column('openinterest', sa.Integer(), nullable=True),
        sa.Column('option_id', sa.Integer(), nullable=True),
        sa.Column('fetch_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['fetch_id'], ['options_fetch.id'], ),
        sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('options_data')
    op.drop_table('options_fetch')
    op.drop_table('options')
    op.drop_table('account_balances')
    op.drop_table('tradables')
    op.drop_table('tokens')
    op.drop_table('accounts')
    # ### end Alembic commands ###
